FROM node:13.12.0
 
RUN mkdir -p /app
 
WORKDIR /app
 
# UPDATED
COPY mern-social/package.json .
 
RUN npm install

# UPDATED
COPY mern-social/ .

RUN npm run build

EXPOSE 3000
 
CMD ["npm", "start"]
